routes:
  /dossiers/:
    controller: channel
    filter: tag:-hash-newsletter
    template: dossiers
    limit: 12

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-hash-newsletter

  /newsletter/:
    permalink: /newsletter/{slug}/
    template: index
    filter: tag:hash-newsletter

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
